### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by n8craig** [PeWu/topola-viewer#170]
How does one address special characters like `ñ` and `à`? I have an instance loaded with a file from a URL but the ñ character is represented as a replacement character `�` (see first image below). I see from the [Skłodowska example](https://pewu.github.io/topola-viewer/#/view?indi=Sk%C5%82odowska-2&source=wikitree) that special characters are possible. If I replace an `ñ` with unicode `U+00F1` it just shows the unicode rather than rendering the character (see second image). Therefore, I am unsure how to implement special characters. Any guidance would be much appreciated.

![image](https://github.com/PeWu/topola-viewer/assets/62002677/1ca3c9b5-3f85-4a21-8912-60bb722350b5)

![image](https://github.com/PeWu/topola-viewer/assets/62002677/e0572957-a3b7-470c-a640-6209f0ef40f9)

**Comment by PeWu** [comment]
I'm not sure why sometimes unicode characters are messed up.
Can you check if your GEDCOM file has a `1 CHAR UTF-8` header and add it if it's not there?

**Comment by PeWu** [comment]
Make  sure the file is actually UTF-8 encoded. Maybe since you had `ANSI` originally, your file is not actually UTF-8. There are various ways of checking it, see https://www.google.com/search?q=check+if+file+is+utf-8
Using a text editor, you may be able to "Save As" using a specific encoding (UTF-8).
Topola Viewer does not support any other encoding than UTF-8.

**Comment by n8craig** [comment]
That was the issue. I opened the `.ged` file in Notepad++ and clicked `Encoding` > `Convert to UTF-8` then I changed `1 CHAR ANSI` to `1 CHAR UTF-8` and the special characters render properly. Thanks for helping to diagnose the issue, which was at my end with the file.
